### ISSUE TITLE
No such module 'ConnectBlu'

### ISSUE THREAD

**Issue by tblx** [MdMugish/BleConnect#2]

**Comment by MdMugish** [comment]
After downloading this project, please add swift package dependency:- https://github.com/MdMugish/BleConnect_Lib

## How to use this :

After pulling this project please import swift package dependency.

Pull this project
Open in XCode
Tap on file
Go to Swift package manager
Tap on Add swift package dependency
Paste this link "https://github.com/MdMugish/BleConnect_Lib"
Next, Next, Finished
Now you can use it (Done)
Swift version must be 5.3.0 or greater

This swift package dependency contains ConnectBlu binary file (Which is XCFramework).
